name: raviqqe/goreleaser-action
description: Goreleaser with automatic Git tagging
branding:
  icon: link
  color: green
inputs:
  version:
    description: A version used as a Git tag.
    required: true
  snapshot:
    description: Dry run.
    required: false
outputs: {}
runs:
  using: composite
  steps:
    - run: git config user.name 'GitHub Action'
      shell: bash
    - run: git config user.email 'action@github.com'
      shell: bash
    - id: tag
      run: echo released=$(git tag -l | grep ${{ inputs.version }}) >> ${{ github.output }}
      shell: bash
    - uses: goreleaser/goreleaser-action@v6
      with:
        args: release ${{ inputs.snapshot && '--snapshot' || '--' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
