name: raviqqe/goreleaser-action
description: Goreleaser with automatic Git tagging
branding:
  icon: link
  color: green
inputs:
  version:
    description: A version used as a Git tag.
    required: true
  snapshot:
    description: Dry run.
    required: false
outputs: {}
runs:
  using: composite
  steps:
    - uses: goreleaser/goreleaser-action@v6
      with:
        args: release ${{ inputs.snapshot && '--snapshot' || '--' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
