name: raviqqe/goreleaser-action
description: Goreleaser with automatic Git tagging
branding:
  icon: link
  color: green
inputs:
  version:
    description: A version used as a Git tag.
    required: true
outputs: {}
runs:
  using: composite
  steps:
    - run: go install github.com/goreleaser/goreleaser/v2@latest
      shell: bash
