name: raviqqe/goreleaser-action
description: Goreleaser with automatic Git tagging
branding:
  icon: link
  color: green
inputs:
  version:
    description: A version used as a Git tag.
    required: true
  snapshot:
    description: Dry run.
    required: false
outputs: {}
runs:
  using: composite
  steps:
    - run: git config user.name 'GitHub Action'
      shell: bash
    - run: git config user.email 'action@github.com'
      shell: bash
    - id: check
      run: >
        echo dry_run=$(
          git tag -l | grep ${{ inputs.version }} ||
          [ "${{ inputs.snapshot }}" = true ] &&
          echo true
        )
        >> ${{ github.output }}
      shell: bash
    - run: git tag ${{ inputs.version }} && git push --tags
      shell: bash
      if: ${{ !steps.check.outputs.dry_run }}
    - uses: goreleaser/goreleaser-action@v6
      with:
        args: release ${{ steps.check.outputs.dry_run && '--snapshot' || '--' }}
